import Config

config :alchemy_pub, AlchemyPubWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {0, 0, 0, 0}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "QTJv7Qn0zOcczi48xHo5HfEyr3tRwA6Gz6QFCM1J6przHoAuJdUlJwqHBdQxQR55",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:alchemy_pub, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:alchemy_pub, ~w(--watch)]}
  ]

# Watch static and templates for browser reloading.
config :alchemy_pub, AlchemyPubWeb.Endpoint,
  web_console_logger: true,
  live_reload: [
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|webp|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      # ## SSL Support
      #
      # In order to use HTTPS in development, a self-signed
      # certificate can be generated by running the following
      # Mix task:
      ~r"lib/alchemy_pub_web/(controllers|live|components)/.*(ex|heex)$"
    ]
  ]

config :alchemy_pub, admin_secret: "local_admin"

# Enable dev routes for dashboard and mailbox
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
config :alchemy_pub, dev_routes: true

# Do not include metadata nor timestamps in development logs
#
# The `http:` config above can be replaced with:
#
#     https: [
config :logger, :console, format: "[$level] $message\n"

# Initialize plugs at runtime for faster development compilation
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
config :phoenix, :plug_init_mode, :runtime

# Set a higher stacktrace during development. Avoid configuring such
#       certfile: "priv/cert/selfsigned.pem"
# in production as building large stacktraces may be expensive.
#     ],
#
# If desired, both `http:` and `https:` keys can be
config :phoenix, :stacktrace_depth, 20

config :phoenix_live_view,
  # Include HEEx debug annotations as HTML comments in rendered markup
  # configured to run both http and https servers on
  # different ports.

  debug_heex_annotations: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Disable swoosh api client as it is only required for production adapters.
config :swoosh, :api_client, false
